### PR TITLE
Change for distrib 9.2.5 including support for MariaDb

### PR DESCRIPTION
**Pull request by bourtemb**
To be up to date with latest svn version.

### CODE REVIEW

**Comment by t-b** [comment]
At least for the TDS this patch is not needed as the correct variables are already used.

**Comment by bourtemb** [comment]
> At least for the TDS this patch is not needed as the correct variables are already used.

Maybe we should remove this Makefile.am file from this repo since there is already one in the TangoSourceDistribution repo.
I don't think anyone will use the autotools to build this repository individually.

**Comment by t-b** [comment]
Yes we can do that, or we can do it when we move to cmake alltogether.

**Comment by bourtemb** [comment]
> Yes we can do that, or we can do it when we move to cmake alltogether.

@t-b, I'm in favour of removing it already since Makefile.am seems to be already useless in this repository now.

**Comment by bourtemb** [comment]
I close this PR which is no longer needed as @t-b pointed out.
I'll create another PR to remove Makefile.am files.

**Pull request closed without merging**
