### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by t-b**
See also https://github.com/tango-controls/TangoSourceDistribution/issues/67#issuecomment-679073793.

### CODE REVIEW

**Comment by t-b** [comment]
@mliszcz @bourtemb I'm not powerful enough to merge or add you as reviewsers.

**Comment by mliszcz** [comment]
LGTM! But I am unable to approve or do any review in this repo.

**Review by bourtemb — APPROVED** [review]
LGTM

**Comment by bourtemb** [comment]
> @mliszcz @bourtemb I'm not powerful enough to merge or add you as reviewsers.

I added the cppTango team as admin for this repo too. You should have enough power to review & merge now I think.

**Pull request merged**
